export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_SCOPES_SUCCESS = "LOAD_SCOPES_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_USER_OPTIMISTIC = "DELETE_USER_OPTIMISTIC";
